### ISSUE TITLE
Wrong result if inside range

### ISSUE THREAD

**Issue by toussii** [AnickaBurova/range-ext#2]
There is some cases that the result will be wrong.
example:
<pre><code>   
match (3..3).intersect(&(3..4)) {
    Intersection::Bellow => println!("Belllow"), // no intersection
    Intersection::BellowOverlap => println!("BelllowOverlap"),
    Intersection::Within => println!("Within"),
    Intersection::Same => println!("Same"),
    Intersection::Over => println!("Over"),
    Intersection::AboveOverlap => println!("AboveOverlap"),
    Intersection::Above => println!("Above"), // no intersection
}
</code></pre>

In here 3 is in the range of 3..4 but the result will be Bellow instead of Within.

**Comment by toussii** [comment]
Found solution ranges are not inclusive so need to add +1 to the range. Would be nice if it also supports inclusive ranges with ..=

**Comment by dereckson** [comment]
> Found solution ranges are not inclusive so need to add +1 to the range. Would be nice if it also supports inclusive ranges with ..=

Could you close your issue in favour of #1? (but not sure if GitHub allows reporter to close their own issues)

**Comment by toussii** [comment]
Thx closed the issue
